name: ci

on: push

env:
  IMAGE_REGISTRY: "ghcr.io"
  REGISTRY_USER: "${{ github.repository_owner }}"
  REGISTRY_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  IMAGE_REPO: "ghcr.io/${{ github.repository_owner }}"
  IMAGE_NAME: "ren_rust"

jobs:
  build_docker_image:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        image_subdir: ["rust_centos7"]


    steps:
    - uses: actions/checkout@v2

    - name: Login docker
      run: |
        echo ${{ env.REGISTRY_TOKEN }} | docker login ${{ env.IMAGE_REGISTRY }} -u ${{ env.REGISTRY_USER }} --password-stdin

    - name: build image
      run: |
        export version=$(jq -r .version rust_centos7/metadata.json)
        echo $version
        export image_full_name=${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ matrix.image_subdir }}_${version}
        docker build -t ${image_full_name} ${{ matrix.image_subdir }}

    - name: Push docker image
      run: |
        docker push ${image_full_name}
        docker manifest inspect ${image_full_name} \
          | jq '[.layers[] | .size] | add' \
          | awk '{print $1/1024/1024}' 

    - name: Test image
      run: |
        docker run ${image_full_name} \
          bash -c "rustc --version && cd /root && cargo new test_1 && cd test_1 && echo 'rand = \"0.8.5\"' >> Cargo.toml && cargo run"
