name: ci

on: push

env:
  IMAGE_REGISTRY: "ghcr.io"
  REGISTRY_USER: "${{ github.repository_owner }}"
  REGISTRY_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  IMAGE_REPO: "ghcr.io/${{ github.repository_owner }}"
  IMAGE_NAME: "ren_rust"

jobs:
  build_docker_image:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        # image_subdir: ["quant_env","ubuntu_x11","arch","centos7"]
        image_subdir: ["centos7"]


    steps:
    - uses: actions/checkout@v2

    - name: Login docker
      run: |
        echo ${{ env.REGISTRY_TOKEN }} | docker login ${{ env.IMAGE_REGISTRY }} -u ${{ env.REGISTRY_USER }} --password-stdin
    - name: build image
      run: |
        docker build -t ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ matrix.image_subdir }} ${{ matrix.image_subdir }}
    - name: Push docker image
      run: |
        docker push ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ matrix.image_subdir }}
        docker manifest inspect ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ matrix.image_subdir }} \
          | jq '[.layers[] | .size] | add' \
          | awk '{print $1/1024/1024}' 

    - name: Test image
      run: |
        docker run ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ matrix.image_subdir }} bash -c "rustc --version"
